config/routes.rb
Ejemplo2I18n::Application.routes.draw do

  scope "(:locale)", :locale => /en|de/ do
    root :to => 'products#index'
    resources :products
  end


end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :name, :price
  validates :name,
            :presence => true,
            :uniqueness => true,
            :length => { :within => 2..255 }

  validates :price,
            :presence => true,
            :numericality => { :greater_than => 0 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_locale

  private

  def extract_locale_from_accept_language_header # pone el idioma automaticamente al usuario segun lo q diga su browser
    request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
    Rails.application.routes.default_url_options[:locale]= I18n.locale
  end

  #mirar abajo de /config/environments/development.rb que es donde se configura el idioma.






end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        #format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.html { redirect_to @product, notice: I18n.t('views.product.flash_messages.product_was_successfully_created') }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        #format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.html { redirect_to @product, notice: I18n.t('views.product.flash_messages.product_was_successfully_updated') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ejemplo2_i18n</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<p>
  <%= link_to_unless I18n.locale == :en, "English", locale: :en %>
  |
  <%= link_to_unless I18n.locale == :de, "Deutsch", locale: :de %>
</p>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <!--<h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>-->
      <h2><%= t 'activerecord.errors.template.header', :model => Product.model_name.human, :count => @product.errors.count %></h2>



      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<!--<h1>Editing product</h1>-->
<h1><%= t 'views.product.edit.title' %></h1>



<%= render 'form' %>

<!--<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>
-->

<%= link_to I18n.t('views.show'), @product %> |
<%= link_to I18n.t('views.back'), products_path %>

app/views/products/index.html.erb
<!--<h1>Listing products</h1>-->
<h1><%= t 'views.product.index.listing_products' %></h1>



<table>
  <tr>
<!--<th>Name</th>
    <th>Description</th>
    <th>Price</th>
-->
    <th><%= Product.human_attribute_name(:name) %></th>
    <th><%= Product.human_attribute_name(:description) %></th>
    <th><%= Product.human_attribute_name(:price) %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.description %></td>
    <td><%= product.price %></td>
<!--
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
-->
    <td><%= link_to I18n.t('views.show'), product %></td>
    <td><%= link_to I18n.t('views.edit'), edit_product_path(product) %></td>
    <td><%= link_to I18n.t('views.destroy'), product, confirm: I18n.t('views.are_you_sure'), method: :delete %></td>

  </tr>
<% end %>
</table>

<br />

<!--<%= link_to 'New Product', new_product_path %>-->
<%= link_to I18n.t('views.product.index.new_product'), new_product_path %>

app/views/products/new.html.erb
<!-- <h1>New product</h1> -->
<h1><%= t 'views.product.new.title' %></h1>



<%= render 'form' %>

<!-- <%= link_to 'Back', products_path %> -->
<%= link_to I18n.t('views.back'), products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<!--  <b>Name:</b>  -->
  <b><%= Product.human_attribute_name(:name) %>:</b>
  <%= @product.name %>
</p>

<p>
<!--  <b>Description:</b> -->
  <b><%= Product.human_attribute_name(:description) %>:</b>
  <%= @product.description %>
</p>

<p>
<!--  <b>Price:</b> -->
  <b><%= Product.human_attribute_name(:price) %>:</b>
  <%= @product.price %>
</p>

<!--
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
-->
<%= link_to I18n.t('views.edit'), edit_product_path(@product) %> |
<%= link_to I18n.t('views.back'), products_path %>